name: Build Images

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
        default: '.'
      image_name:
        required: true
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image
        run: |
          docker build -f ${{ inputs.dockerfile_path }} -t docconman/${{ inputs.image_name }}:latest
          docker push docconman/${{ inputs.image_name }}:latest
