ec2_instances:
  - name: "example-prod-ec2-instance-1"
    instance_type: "t2.micro"
    key_name: "user1"
    monitoring: true
    vpc_security_group_ids:
      - "sg-12345678"
    subnet_id: "subnet-eddcdzz4"
    tags:
      Owner: "Alice"
  - name: "example-prod-ec2-instance-2"
    instance_type: "t3.small"
    key_name: "user2"
    monitoring: false
    vpc_security_group_ids:
      - "sg-87654321"
    subnet_id: "subnet-xyzabcd"
    tags:
      Owner: "Bob"