site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/ju0000/portfolio
#edit_uri: edit/main/docs

#sidebar navigation
nav:
  - 개요:
    - 백스테이지가 무엇인가요?: 'index.md'
  - 백스테이지 구성 항목:
    - Catalog: 'catalog.md'
    - APIs: 'api.md'
    - Docs: 'docs.md'
    - Create: 'create.md'
