apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-configmap
data:
  BACKSTAGE_HOST: idp.portfolio.xyz
  ARGOCD_PROD_URL: https://argocd.portfolio.xyz
  POSTGRES_HOST: postgres.backstage.svc.cluster.local
  POSTGRES_PORT: "5432"
  AWS_REGION: ap-northeast-2
  ROLE_NAME_TO_ASSUME: ""