apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

namespace: backstage

resources:
- ../../base
- configmap.yaml
- secrets.yaml

images:
- name: docconman/backstage-portfolio
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: backstage
    backstage.io/kubernetes-id: backstage

patches:
- path: deployment-env-patch.yaml
- path: deployment-replica-patch.yaml
- path: deployment-resource-patch.yaml
- path: service-patch.yaml
