vpc:
  name: "dev-vpc"
  cidr: "10.0.0.0/16"
  azs: ["ap-northeast-2a", "ap-northeast-2c"]
  private_subnets: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets: ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
  private_subnet_names: ["private-subnet-dev-a-1", "private-subnet-dev-c-2", "private-subnet-dev-a-3"]
  public_subnet_names: ["public-subnet-dev-a-1", "public-subnet-dev-c-2", "public-subnet-dev-a-3"]
  enable_nat_gateway: true
  single_nat_gateway: true
  enable_vpn_gateway: true
  tags:
    Owner: "DevOps Team"