vpc:
  name: "prod-vpc"
  cidr: "10.1.0.0/16"
  azs: ["ap-northeast-2a", "ap-northeast-2c"]
  private_subnets: ["10.1.1.0/24", "10.1.2.0/24", "10.1.3.0/24"]
  public_subnets: ["10.1.101.0/24", "10.1.102.0/24", "10.1.103.0/24"]
  private_subnet_names: ["private-subnet-prod-a-1", "private-subnet-prod-c-2", "private-subnet-prod-a-3"]
  public_subnet_names: ["public-subnet-prod-a-1", "public-subnet-prod-c-2", "public-subnet-prod-a-3"]
  enable_nat_gateway: true
  single_nat_gateway: true
  enable_vpn_gateway: true
  tags:
    Owner: "DevOps Team"