apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

namespace: ${{values.repoName}}

resources:
- ../../base
- configmap.yaml
- secrets.yaml

images:
- name: docconman/${{values.repoName}}
  newTag: latest

labels:
- includeSelectors: true
  pairs:
    app: ${{values.repoName}}
    backstage.io/kubernetes-id: ${{values.repoName}}

patches:
- path: deployment-env-patch.yaml
- path: deployment-replica-patch.yaml
- path: deployment-resource-patch.yaml
- path: service-patch.yaml
