apiVersion: v1
kind: Pod
metadata:
  name: myclient2
  labels:
    app: myclient
spec:
#  nodeName: k8s-m
  containers:
    - name: myclient2
      image: bitnami/kafka:3.2
      command: ["tail"]
      args: ["-f", "/dev/null"]
  terminationGracePeriodSeconds: 0