apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.repoName}}
  namespace: ${{values.namespace}}
secrets:
  - name: ${{values.repoName}}-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.repoName}}-sa-token
  namespace: ${{values.namespace}}
  annotations:
    kubernetes.io/service-account.name: ${{values.repoName}}
type: kubernetes.io/service-account-token