# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  template:
    spec:
      containers:
        - name: teste
          image: 
          ports:
            - name: http
              containerPort: 8080