apiVersion: v1
kind: ServiceAccount
metadata:
  name: teste
  namespace: app
secrets:
  - name: teste-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: teste-sa-token
  namespace: app
  annotations:
    kubernetes.io/service-account.name: teste
type: kubernetes.io/service-account-token