$ansible_ip = "192.168.33.100"
$managed_ip = "192.168.33.10"
$managed_count = 2

Vagrant.configure("2") do |config|
# ansible control node
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "bento/ubuntu-20.04-arm64"
    ansible.vm.network "private_network", ip: $ansible_ip
    ansible.vm.provider "vmware_desktop" do |vmware|
      # Display the VirtualBox GUI when booting the machine
      vmware.gui = true
      vmware.vmx["memsize"] = "4096"
      vmware.vmx["numvcpus"] = "2"
    end
    ansible.vm.hostname = "ansible"
  end

# ansible managed node
  (1..$managed_count).each do |i|
    config.vm.define "managed#{i}" do |managed|
      managed.vm.box = "bento/ubuntu-20.04-arm64"
      managed.vm.network "private_network", ip: "#{$managed_ip}#{i}"
      managed.vm.provider "vmware_desktop" do |vmware|
        vmware.gui = true
        vmware.vmx["memsize"] = "4096"
        vmware.vmx["numvcpus"] = "2"
      end
      managed.vm.hostname = "managed#{i}"
    end
  end
end
