apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
  description: A collection of all templates
spec:
  targets:
    - ./scaffolder-templates/create-springboot-app/template.yaml
    - ./scaffolder-templates/create-nodejs-app/template.yaml
    - ./scaffolder-templates/create-argocd-app/template.yaml
    - ./scaffolder-templates/create-aws-s3/template.yaml