apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  title: PostgreSQL
  description: PostgreSQL is a powerful, open source object-relational database system.
  links:
    - url: https://access.crunchydata.com/documentation/postgres-operator/v5/
      title: Documentation
      icon: web
spec:
  type: database
  lifecycle: production
  owner: team-devops 
  system: backstage-portfolio