name: Build and Deploy Backstage

on:
  # push:
  #   branches:
  #     - develop
  #   paths:
  #     - 'idp/backstage/**'
  workflow_dispatch:
    inputs:
      image_type:
        required: true
        type: string
        default: 'backstage'

jobs:
  call_workflow:
    uses: ./.github/workflows/re-build-images.yaml
    with:
      dockerfile_path: 'idp/backstage/backstage-portpolio/Dockerfile'
      image_type: '${{ inputs.image_type }}'
      image_name: 'backstage-portpolio'
    secrets: inherit