name: Build and Deploy Kafka Plugin

on:
  push:
    branches:
      - develop
    paths:
      - 'ops-tools/helm/kafka/kafka-crd/plugin/**'
  workflow_dispatch:
    inputs:
      image_type:
        required: true
        type: string
        default: 'kafka-connector'

jobs:
  call_workflow:
    uses: ./.github/workflows/re-build-images.yaml
    with:
      dockerfile_path: 'ops-tools/helm/kafka/kafka-crd/connector/Dockerfile'
      image_type: '${{ inputs.image_type }}'
      image_name: 'kafka-connector-3.8.0'
    secrets: inherit
