name: Deploy ArgoCD

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
        default: '.'
      image_name:
        required: true
        type: string

jobs:
  deploy_argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ArgoCD
        run: |
          echo "Deploying ArgoCD"
